### ISSUE TITLE
Windows - Client crashes immediantly at startup

### ISSUE THREAD

**Issue by ApertureDevelopment** [TeaSpeak/TeaClient#35]
Hello there,

So I am unable to open the TeaSpeak client at all, whenever I try a tab in the taskbar pops up shortly and instantly disapears ( assuming the client opens but crashes before it can load any UI ). After starting up the client using the console, I recieved the following log:

```
Native module path: E:\Program Files (x86)\TeaSpeak\Client\resources\natives
Versions:
  TeaSpeak Client: 1.4.8
  node: 12.13.0
  v8: 8.0.426.16-electron.0
  uv: 1.32.0
  zlib: 1.2.11
  brotli: 1.0.7
  ares: 1.15.0
  modules: 76
  nghttp2: 1.39.2
  napi: 5
  llhttp: 1.1.4
  http_parser: 2.8.0
  openssl: 1.1.0
  icu: 65.1
  unicode: 12.1
  electron: 8.0.0
  chrome: 80.0.3987.86
Parsed CMD arguments [
  'E:\\Program Files (x86)\\TeaSpeak\\Client\\TeaClient.exe',
  [length]: 1
] as {
  _: [ [length]: 0 ],
  '--': [ [length]: 0 ],
  has_flag: [Function] { [length]: 0, [name]: '' },
  value: [Function] { [length]: 0, [name]: '' },
  has_value: [Function] { [length]: 0, [name]: '' }
}
Main app executed!
Parsed CMD arguments [
  'E:\\Program Files (x86)\\TeaSpeak\\Client\\TeaClient.exe',
  [length]: 1
] as {
  _: [ [length]: 0 ],
  '--': [ [length]: 0 ],
  has_flag: [Function] { [length]: 0, [name]: '' },
  value: [Function] { [length]: 0, [name]: '' },
  has_value: [Function] { [length]: 0, [name]: '' }
}
Setting up render backend
Spawn loading screen
Open UI loader window.
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
request: http://clientapi.teaspeak.de//api.php?type=update-info
Uncaught Exception thrown:
TypeError: Error processing argument at index 1, conversion failure from
    at BrowserWindow.<anonymous> (E:\Program Files (x86)\TeaSpeak\Client\resources\app.asar\modules\core\ui-loader\graphical.js:117:17)
    at BrowserWindow.emit (events.js:210:5)
Shutting down app.
App has been finalized.
```

I am using Windows 10 Pro, Rev. 1909

**Comment by WolverinDEV** [comment]
> TypeError: Error processing argument at index 1, conversion failure from

This one is quite interesting.
I've already seen that some time ago, so I'm a bit confused ;)

**Comment by WolverinDEV** [comment]
Should be fixed (Re - download the 1.4.8 and reinstall it)

**Comment by ApertureDevelopment** [comment]
Nope, I still can't open it. I re-downloaded it from https://teaspeak.de/ and completely removed it and installed it. I get the same error message

**Comment by WolverinDEV** [comment]
Well with the next release 1.4.10 I've added a try catch and everything should work ;)
Stay tuned for the release, think I'll publish it tomorrow.
